{% set name = "google-cloud-websecurityscanner" %}
{% set version = "1.14.5" %}
{% set sha256 = "1f6c810258ed05a276dfe6340008bdc2ee660bab2886fb8948e4cdaadbc6023b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=1.15.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - google.cloud.websecurityscanner
    - google.cloud.websecurityscanner_v1
    - google.cloud.websecurityscanner_v1alpha
    - google.cloud.websecurityscanner_v1beta

about:
  home: https://github.com/googleapis/python-websecurityscanner
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Web Security Scanner API client library
  description: "Google Cloud Web Security Scanner API scans your Compute and App Engine apps for common web vulnerabilities.\n[Quick start guide](https://googleapis.dev/python/websecurityscanner/latest/index.html#quick-start)"

  doc_url: https://googleapis.dev/python/websecurityscanner/latest/index.html
  dev_url: https://github.com/googleapis/python-websecurityscanner

extra:
  recipe-maintainers:
    - parthea
