{% set name = "google-cloud-websecurityscanner" %}
{% set version = "1.3.0" %}
{% set sha256 = "632ac3c50eee704ed2a6e87d5a09379589841cf53459813c76f8bea01e77c49d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip >=18.1
  run:
    - python
    - google-api-core-grpc >=1.14.0,<2.0.0dev

test:
  imports:
    - grpc
    - google.cloud.websecurityscanner
    - google.cloud.websecurityscanner_v1beta

about:
  home: https://github.com/googleapis/python-websecurityscanner
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Web Security Scanner API client library
  description: "Google Cloud Web Security Scanner API scans your Compute and App Engine apps for common web vulnerabilities.\n[Quick start guide](https://googleapis.dev/python/websecurityscanner/latest/index.html#quick-start)"

  doc_url: https://googleapis.dev/python/websecurityscanner/latest/index.html
  dev_url: https://github.com/googleapis/python-websecurityscanner

extra:
  recipe-maintainers:
    - parthea
